builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

brews:
  - name: vaultx
    url_template: https://github.com/razahuss02/vaultx/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/razahuss02/vaultx"
    install: |
      bin.install "vaultx"
    repository:
      owner: razahuss02
      name: vaultx
      token: "{{ .Env.GITHUB_TOKEN }}"