repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: go-mod-tidy
      - id: go-fmt
      - id: go-lint
      - id: golangci-lint
      - id: go-imports