# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultx < Formula
  desc ""
  homepage "https://github.com/razahuss02/vaultx"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/razahuss02/vaultx/releases/download/v1.0.0/vaultx_1.0.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e2c4f98fce87bbee67bc17e13e0c750c654ba7b22436e2735334982be7dd1621"

      def install
        bin.install "vaultx_1.0.0_darwin_amd64.tar.gz" => "vaultx"
      end
    end
    on_arm do
      url "https://github.com/razahuss02/vaultx/releases/download/v1.0.0/vaultx_1.0.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "520835c5e93aae2c66c6572eba5a3eafd6557b52ea4b3e7e94fe9e36bf041b83"

      def install
        bin.install "vaultx_1.0.0_darwin_arm64.tar.gz" => "vaultx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/razahuss02/vaultx/releases/download/v1.0.0/vaultx_1.0.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "61ec66cf1fff90b2934dbb9b9dc5db8fd6ba2fb2f9151e8f7892f12ab8672107"

        def install
          bin.install "vaultx_1.0.0_linux_amd64.tar.gz" => "vaultx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/razahuss02/vaultx/releases/download/v1.0.0/vaultx_1.0.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "3931378c10302b7e6e78590756e4ade5c3bda16cca02ffb18c36b192c8591802"

        def install
          bin.install "vaultx_1.0.0_linux_arm64.tar.gz" => "vaultx"
        end
      end
    end
  end
end
