# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultx < Formula
  desc ""
  homepage "https://github.com/razahuss02/vaultx"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/razahuss02/vaultx/releases/download/v1.0.1/vaultx_1.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "bb469deaac82e0546e23bb8dd5c5d433c66c43ace87379fcc8dc71f8a205441b"

      def install
        bin.install "vaultx"
      end
    end
    on_arm do
      url "https://github.com/razahuss02/vaultx/releases/download/v1.0.1/vaultx_1.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d976890778add41f991c77cdbc4cac71784340eb0e9a6c55f1137fdfbd2537d6"

      def install
        bin.install "vaultx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/razahuss02/vaultx/releases/download/v1.0.1/vaultx_1.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "9449919f4e55ac8ba863017180ccb688d7bf0c2ef60d0da9b57bc2e0352eb95a"

        def install
          bin.install "vaultx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/razahuss02/vaultx/releases/download/v1.0.1/vaultx_1.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "014253f54bce90b84c9479c347a59495aa584e24d9bddafebf84fe2eb5eac383"

        def install
          bin.install "vaultx"
        end
      end
    end
  end
end
